version: 0.2

phases:
  pre_build:
    commands:
  build:
    commands:
      - cd docs/
      - pip install -r requirements.txt
      - make html

  post_build:
    commands:
      - aws s3 cp .build/html s3://$BUCKET --recursive